export const FETCH_CURRENT_WEATHER_START = 'FETCH_CURRENT_WEATHER_START';
export const FETCH_CURRENT_WEATHER_SUCCESS = 'FETCH_CURRENT_WEATHER_SUCCESS';
export const FETCH_CURRENT_WEATHER_FAILED = 'FETCH_CURRENT_WEATHER_FAILED';
export const SET_LOCATION = 'SET_LOCATION';
