export const FETCH_CURRENT_WEATHER_START = 'FETCH_CURRENT_WEATHER_START';
export const FETCH_CURRENT_WEATHER_SUCCESS = 'FETCH_CURRENT_WEATHER_SUCCESS';
export const FETCH_CURRENT_WEATHER_FAILED = 'FETCH_CURRENT_WEATHER_FAILED';
export const FETCH_FORECAST_START = 'FETCH_FORECAST_START';
export const FETCH_FORECAST_SUCCESS = 'FETCH_FORECAST_SUCCESS';
export const FETCH_FORECAST_FAILED = 'FETCH_FORECAST_FAILED';
export const SET_LOCATION = 'SET_LOCATION';
export const CHANGE_TEMP_UNIT = 'CHANGE_TEMP_UNIT';
